name: local
variables:
  - name: bruno_echo_url
    value: https://echo.usebruno.com
    enabled: true
    secret: false
    type: text
  - name: platform_name
    value: Bruno Desktop
    enabled: true
    secret: false
    type: text
  - name: target_environment
    value: local
    enabled: true
    secret: false
    type: text
  - name: build_id
    value: local-run-001
    enabled: true
    secret: false
    type: text
  - name: commit_sha
    value: local-demo-sha
    enabled: true
    secret: false
    type: text
  - name: demo_owner
    value: bruno-devrel
    enabled: true
    secret: false
    type: text
